---
logic:
  questHistoryLimit: 90 # for how many days soft-deleted quests are retained
  punishments:
    # in trust percents; order: for early change, for late change, for change when already overdue
    changeDeadline:
      - 0
      - 1
      - 2
  formulas:
    userLeveling:
      main:
        levelFactor: 9.71572
        growthRate: 2.1
        roundingIncrement: 50
      skill:
        levelFactor: 5.75804
        growthRate: 2.1
        roundingIncrement: 50
    # by rarity from 0 (common) to 2 (legendary)
    catBoosts:
      0:
        base: 5
        limit: 10
        growthRate: 2
        roundingIncrement: 0.01
      1:
        base: 10
        limit: 20
        growthRate: 2
        roundingIncrement: 0.01
      2:
        base: 20
        limit: 40
        growthRate: 2
        roundingIncrement: 0.01
    catReturnPrices:
      0:
        base: 50
        limit: 200
        growthRate: 1.5
        roundingIncrement: 0.01
      1:
        base: 100
        limit: 400
        growthRate: 1.5
        roundingIncrement: 0.01
      2:
        base: 200
        limit: 800
        growthRate: 1.5
        roundingIncrement: 0.01
  cases:
    common:
      price: 100 # in feed
      rarePercentage: 12
      legendaryPercentage: 3
    legendary:
      price: 20 # in catnip
      rarePercentage: 50
      legendaryPercentage: 30

openapi:
  title: Purriorities API
  description: The API for the Purriorities gamified task manager.
  version: 0.0.1
  excludedSchemas:
    - User
    - Category
    - Quest
    - Stage
    - Task
    - Skill
    - QuestSkill
    - Cat
    - CatOwnership
