# Create a copy, rename to your deployment environment and fill with your own values
# Can also be used to override configs in common.yaml, because configs from environment-specific file take precedence
---
http:
  port: 80
  serveStaticPath: purriorities-frontend/build/web

database:
  host: localhost
  port: 33080
  username: root
  password: root
  database: purriorities
